/* ==========================
   ACQUISITION WORKSPACE
========================== */

const acquisitionState = {
  loaded: false,
  loading: false,
  error: null,
  raw: null,
  filters: {
    search: "",
    week: "all",
    de: "all",
    client: "all"
  },
  historyFilters: {
    search: "",
    document: "all",
    month: "all"
  },
  quietRender: false
};

function carregarAcquisition(force = false) {
  if (!force && (acquisitionState.loaded || acquisitionState.loading)) {
    return Promise.resolve(acquisitionState);
  }

  acquisitionState.loading = true;
  acquisitionState.error = null;
  renderAcquisition();

  return firebase.firestore()
    .collection("acquisition")
    .doc("acquisition")
    .get()
    .then(doc => {
      acquisitionState.loading = false;
      acquisitionState.loaded = true;

      if (!doc.exists) {
        acquisitionState.raw = null;
        return acquisitionState;
      }

      const item = doc.data();
      acquisitionState.raw = _parseAcquisitionJson(item.jsonCompleto || item);
      return acquisitionState;
    })
    .catch(error => {
      acquisitionState.loading = false;
      acquisitionState.loaded = true;
      acquisitionState.error = error;
      acquisitionState.raw = null;
      console.error("Acquisition load error:", error);
      return acquisitionState;
    })
    .finally(renderAcquisition);
}

function abrirAcquisition() {
  if (!acquisitionState.loaded && !acquisitionState.loading) {
    carregarAcquisition();
  } else {
    renderAcquisition();
  }
}

function resetarFiltrosAcquisition() {
  acquisitionState.filters = {
    search: "",
    week: "all",
    de: "all",
    client: "all"
  };

  acquisitionState.historyFilters = {
    search: "",
    document: "all",
    month: "all"
  };

  acquisitionState.quietRender = false;
}

function renderAcquisition() {
  const sec = document.getElementById("acquisition-section");
  if (!sec) return;
  const shellClass =
    acquisitionState.quietRender
      ? "acquisition-shell acquisition-shell-quiet"
      : "acquisition-shell";

  if (acquisitionState.loading) {
    sec.innerHTML = `
      <div class="${shellClass}">
        ${_renderAcquisitionHero(null)}
        ${_renderAcquisitionLoading()}
      </div>
    `;
    return;
  }

  if (acquisitionState.error) {
    sec.innerHTML = `
      <div class="${shellClass}">
        ${_renderAcquisitionHero(null)}
        <div class="acquisition-panel">
          <div class="acquisition-empty">
            <i class="fa-solid fa-triangle-exclamation"></i>
            <strong>Acquisition database unavailable</strong>
            <span>Check Firestore document acquisition/acquisition.</span>
          </div>
        </div>
      </div>
    `;
    return;
  }

  const data = _normalizeAcquisitionData(acquisitionState.raw);

  if (!data.projects.length) {
    sec.innerHTML = `
      <div class="${shellClass}">
        ${_renderAcquisitionHero(data)}
        <div class="acquisition-panel">
          <div class="acquisition-empty">
            <i class="fa-solid fa-file-contract"></i>
            <strong>No acquisition JSON loaded yet</strong>
            <span>Create acquisition/acquisition with jsonCompleto generated by the macro.</span>
          </div>
        </div>
      </div>
    `;
    _bindAcquisitionEvents();
    return;
  }

  const filtered = _filterAcquisitionData(data);
  const docs = _flattenAcquisitionDocs(filtered.projects);

  sec.innerHTML = `
    <div class="${shellClass}">
      ${_renderAcquisitionHero(data)}
      ${_renderAcquisitionKpis(docs)}
      ${_renderAcquisitionControls(data)}
      <div class="acquisition-grid">
        ${_renderActionBoard(docs)}
        <div class="acquisition-side-stack">
          ${_renderManagementTable("Workload by DE", _groupAcquisitionDocs(docs, "de"))}
          ${_renderManagementTable("Client pressure", _groupAcquisitionDocs(docs, "client"))}
          ${_renderCompletedHistoryPanel(docs)}
          ${_renderInactiveOverduePanel(docs)}
        </div>
      </div>
    </div>
  `;

  _bindAcquisitionEvents();
}

function _parseAcquisitionJson(jsonCompleto) {
  if (!jsonCompleto) return null;
  if (typeof jsonCompleto !== "string") return jsonCompleto;

  try {
    return JSON.parse(jsonCompleto);
  } catch (error) {
    try {
      return JSON.parse(jsonCompleto.replace(/'/g, '"'));
    } catch {
      throw error;
    }
  }
}

function _normalizeAcquisitionData(raw) {
  const data = raw || {};
  const projects = _extractAcquisitionProjects(data).map(project => ({
    id: project.id || _normalizarAcquisitionId(project.project || project.projeto || project.nome),
    client: project.client || project.cliente || "",
    project: project.project || project.projeto || project.nome || "",
    de: _normalizeAcquisitionPerson(project.de || project.DE || project.responsible || ""),
    status: project.status || "",
    documents: _extractAcquisitionDocuments(project)
  })).filter(project => project.project);

  return {
    version: data.version || "acquisition-v1",
    generatedAt: data.generatedAt || data.lastGlobalUpdate || "",
    metadata: data.metadata || {},
    summary: data.summary || {},
    projects
  };
}

function _extractAcquisitionProjects(raw) {
  if (!raw) return [];
  if (Array.isArray(raw)) return raw;
  if (Array.isArray(raw.projects)) return raw.projects;
  if (Array.isArray(raw.projetos)) return raw.projetos;
  if (raw.projects && typeof raw.projects === "object") {
    return Object.entries(raw.projects).map(([id, value]) => ({ id, ...value }));
  }
  return [];
}

function _extractAcquisitionDocuments(project) {
  const docs = project.documents || project.documentos || [];
  if (!Array.isArray(docs)) return [];

  return docs.map(doc => {
    const state = doc.state || doc.bucket || "future";
    return {
      name: doc.name || doc.nome || doc.document || "",
      dueDate: doc.dueDate || doc.data || "",
      week: Number(doc.week || doc.semana || 0),
      state,
      bucket: doc.bucket || state,
      daysFromToday: Number(doc.daysFromToday ?? _daysFromToday(doc.dueDate || doc.data)),
      sourceStatus: doc.sourceStatus || doc.status || ""
    };
  }).filter(doc => doc.name && doc.dueDate);
}

function _flattenAcquisitionDocs(projects) {
  return projects.flatMap(project =>
    project.documents.map(doc => ({
      ...doc,
      projectId: project.id,
      project: project.project,
      client: project.client,
      de: project.de,
      projectStatus: project.status
    }))
  ).sort((a, b) => {
    const stateOrder = { overdue: 0, onTime: 1, future: 2, completed: 3 };
    const stateDiff = (stateOrder[a.state] ?? 9) - (stateOrder[b.state] ?? 9);
    if (stateDiff !== 0) return stateDiff;
    return _parseAcquisitionDate(a.dueDate) - _parseAcquisitionDate(b.dueDate);
  });
}

function _filterAcquisitionData(data) {
  const filters = acquisitionState.filters;
  const term = _normalizeAcquisitionSearch(filters.search);

  const projects = data.projects.map(project => ({
    ...project,
    documents: project.documents.filter(doc => {
      if (filters.week !== "all" && String(doc.week) !== String(filters.week)) return false;
      if (filters.de !== "all" && project.de !== filters.de) return false;
      if (filters.client !== "all" && project.client !== filters.client) return false;
      if (!term) return true;
      return _normalizeAcquisitionSearch(`${project.project} ${project.client} ${project.de} ${doc.name}`).includes(term);
    })
  })).filter(project => project.documents.length);

  return { ...data, projects };
}

function _renderAcquisitionHero(data) {
  const metadata = data?.metadata || {};
  const generated = _formatAcquisitionDateTime(data?.generatedAt);
  const sourceWeek = metadata.sourceWeek ? `cw${String(metadata.sourceWeek).padStart(2, "0")}` : "Not loaded";
  const actionWeek = metadata.actionWeek ? `w${String(metadata.actionWeek).padStart(2, "0")}` : "Not loaded";

  return `
    <section class="acquisition-hero">
      <div>
        <span class="acquisition-eyebrow">Acquisition</span>
        <h2>Quotation Follow-up</h2>
        <p>Operational view for Development Engineers and management summary for acquisition document timing.</p>
        <div class="acquisition-meta">
          <span class="acquisition-pill">Source: ${_escapeAcquisition(sourceWeek)}</span>
          <span class="acquisition-pill">Action week: ${_escapeAcquisition(actionWeek)}</span>
          <span class="acquisition-pill">Updated: ${_escapeAcquisition(generated)}</span>
        </div>
      </div>
      <button class="acquisition-refresh-btn" id="acquisitionRefreshBtn" type="button">
        <i class="fa-solid fa-rotate-right"></i>
        Refresh
      </button>
    </section>
  `;
}

function _renderAcquisitionLoading() {
  if (typeof renderSiteLoading === "function") {
    return renderSiteLoading("Loading acquisition", "Fetching quotation follow-up data from Firestore.");
  }
  return `<div class="site-loading" data-loading="true"><strong>Loading acquisition</strong></div>`;
}

function _renderAcquisitionKpis(docs) {
  const counts = _countAcquisitionStates(docs);
  const active = counts.overdue + counts.onTime + counts.future;
  const completion = docs.length ? Math.round((counts.completed / docs.length) * 100) : 0;

  return `
    <section class="acquisition-kpi-grid">
      ${_renderAcquisitionKpi("Active", active, "documents to manage")}
      ${_renderAcquisitionKpi("Overdue", counts.overdue, "needs escalation", "overdue")}
      ${_renderAcquisitionKpi("On time", counts.onTime, "due within 7 days", "ontime")}
      ${_renderAcquisitionKpi("Future", counts.future, "scheduled later", "future")}
      ${_renderAcquisitionKpi("Completed", counts.completed, "history for management", "completed")}
      ${_renderAcquisitionKpi("Completion", `${completion}%`, "of listed documents")}
    </section>
  `;
}

function _renderAcquisitionKpi(label, value, hint, tone = "") {
  return `
    <div class="acquisition-kpi ${tone}">
      <span>${_escapeAcquisition(label)}</span>
      <strong>${_escapeAcquisition(value)}</strong>
      <small>${_escapeAcquisition(hint)}</small>
    </div>
  `;
}

function _renderAcquisitionControls(data) {
  const weeks = [...new Set(_flattenAcquisitionDocs(data.projects).map(doc => doc.week).filter(Boolean))].sort((a, b) => a - b);
  const des = [...new Set(data.projects.map(project => project.de).filter(_isValidAcquisitionPerson))].sort((a, b) => a.localeCompare(b));
  const clients = [...new Set(data.projects.map(project => project.client).filter(Boolean))].sort((a, b) => a.localeCompare(b));
  const filters = acquisitionState.filters;
  if (filters.de !== "all" && !des.includes(filters.de)) filters.de = "all";

  return `
    <section class="acquisition-controls">
      <label class="acquisition-control">
        <i class="fa-solid fa-magnifying-glass"></i>
        <input id="acquisitionSearch" type="search" placeholder="Search project, client, DE or document..." value="${_escapeAcquisition(filters.search)}">
      </label>
      ${_renderAcquisitionSelect("acquisitionWeek", "fa-calendar-week", filters.week, [["all", "All weeks"], ...weeks.map(week => [String(week), `w${String(week).padStart(2, "0")}`])])}
      ${_renderAcquisitionSelect("acquisitionDe", "fa-user-tie", filters.de, [["all", "All DEs"], ...des.map(de => [de, de])])}
      ${_renderAcquisitionSelect("acquisitionClient", "fa-building", filters.client, [["all", "All clients"], ...clients.map(client => [client, client])])}
    </section>
  `;
}

function _renderAcquisitionSelect(id, icon, value, options) {
  return `
    <label class="acquisition-control">
      <i class="fa-solid ${icon}"></i>
      <select id="${id}">
        ${options.map(([optionValue, label]) => `
          <option value="${_escapeAcquisition(optionValue)}" ${String(value) === String(optionValue) ? "selected" : ""}>${_escapeAcquisition(label)}</option>
        `).join("")}
      </select>
    </label>
  `;
}

function _renderActionBoard(docs) {
  const activeDocs = docs.filter(doc =>
    doc.state !== "completed" &&
    !(doc.state === "overdue" && !_isAcquisitionOnGoing(doc.projectStatus))
  );
  return `
    <section class="acquisition-panel">
      <div class="acquisition-panel-header">
        <div>
          <h3>Action Board</h3>
          <p>Documents still requiring attention, separated by urgency.</p>
        </div>
        <span class="acquisition-count">${activeDocs.length} active</span>
      </div>
      <div class="acquisition-action-groups">
        ${_renderActionGroup("Future", "fa-calendar-plus", activeDocs.filter(doc => doc.state === "future"))}
        ${_renderActionGroup("On time", "fa-clock", activeDocs.filter(doc => doc.state === "onTime"))}
        ${_renderActionGroup("Overdue", "fa-triangle-exclamation", activeDocs.filter(doc => doc.state === "overdue"))}
      </div>
    </section>
  `;
}

function _renderActionGroup(title, icon, docs) {
  return `
    <div class="acquisition-action-group">
      <h4><i class="fa-solid ${icon}"></i>${_escapeAcquisition(title)} <span>${docs.length}</span></h4>
      <div class="acquisition-action-list">
        ${docs.length ? _groupDocsByProject(docs).map(_renderActionProject).join("") : _renderAcquisitionEmptySmall("No documents in this group.", true)}
      </div>
    </div>
  `;
}

function _renderActionProject(group) {
  return `
    <article class="acquisition-action-card">
      <div>
        <div class="acquisition-project-name">${_escapeAcquisition(group.project)}</div>
        <div class="acquisition-project-meta">
          <span>${_escapeAcquisition(group.client || "No client")}</span>
          <span>${_escapeAcquisition(group.de || "No DE")}</span>
          <span>${_escapeAcquisition(group.status || "No status")}</span>
        </div>
      </div>
      <div class="acquisition-doc-stack">
        ${group.docs.map(doc => `
          <span class="acquisition-doc-tile ${_escapeAcquisition(doc.state)}"><strong>${_escapeAcquisition(doc.name)}</strong><small>${_escapeAcquisition(_formatAcquisitionDate(doc.dueDate))}</small></span>
        `).join("")}
      </div>
    </article>
  `;
}

function _renderManagementTable(title, rows) {
  const limited = rows.slice(0, 8);
  return `
    <section class="acquisition-table-card">
      <h3>${_escapeAcquisition(title)}</h3>
      ${limited.length ? `
        <table class="acquisition-mini-table">
          <thead><tr><th>Name</th><th>Active</th><th>Overdue</th></tr></thead>
          <tbody>
            ${limited.map(row => `
              <tr>
                <td>${_escapeAcquisition(row.name || "Not defined")}</td>
                <td>${row.active}</td>
                <td>${row.overdue}</td>
              </tr>
            `).join("")}
          </tbody>
        </table>
      ` : _renderAcquisitionEmptySmall("No rows for current filters.")}
    </section>
  `;
}

function _renderCompletedHistoryPanel(docs) {
  const completedBase = docs
    .filter(doc => doc.state === "completed")
    .sort((a, b) => _parseAcquisitionDate(b.dueDate) - _parseAcquisitionDate(a.dueDate));
  const filters = acquisitionState.historyFilters;
  const documents = [...new Set(completedBase.map(doc => doc.name).filter(Boolean))].sort((a, b) => a.localeCompare(b));
  const months = [...new Map(completedBase
    .map(doc => [_formatAcquisitionMonthKey(doc.dueDate), _formatAcquisitionMonthLabel(doc.dueDate)])
    .filter(([key]) => key)
  )].sort((a, b) => b[0].localeCompare(a[0]));

  if (filters.document !== "all" && !documents.includes(filters.document)) filters.document = "all";
  if (filters.month !== "all" && !months.some(([key]) => key === filters.month)) filters.month = "all";

  const term = _normalizeAcquisitionSearch(filters.search);
  const completed = completedBase
    .filter(doc => filters.document === "all" || doc.name === filters.document)
    .filter(doc => filters.month === "all" || _formatAcquisitionMonthKey(doc.dueDate) === filters.month)
    .filter(doc => {
      if (!term) return true;
      return _normalizeAcquisitionSearch(`${doc.project} ${doc.client} ${doc.de} ${doc.name}`).includes(term);
    });

  return `
    <section class="acquisition-table-card acquisition-history-card">
      <div class="acquisition-history-heading">
        <h3>Completed History</h3>
        <span class="acquisition-count">${completed.length} shown</span>
      </div>
      <div class="acquisition-history-controls">
        <label class="acquisition-control acquisition-history-search">
          <i class="fa-solid fa-magnifying-glass"></i>
          <input id="acquisitionHistorySearch" type="search" placeholder="Search DE, document, client or project..." value="${_escapeAcquisition(filters.search)}">
        </label>
        ${_renderAcquisitionSelect("acquisitionHistoryDocument", "fa-file-lines", filters.document, [["all", "All documents"], ...documents.map(document => [document, document])])}
        ${_renderAcquisitionSelect("acquisitionHistoryMonth", "fa-calendar-days", filters.month, [["all", "All months"], ...months])}
      </div>
      <div class="acquisition-history-list">
        ${completed.length ? completed.map(doc => `
          <div class="acquisition-history-item">
            <strong>${_escapeAcquisition(doc.project)}</strong>
            <span>${_escapeAcquisition(doc.name)} - ${_escapeAcquisition(doc.client)} - ${_escapeAcquisition(doc.de || "No DE")} - ${_escapeAcquisition(_formatAcquisitionDate(doc.dueDate))}</span>
          </div>
        `).join("") : _renderAcquisitionEmptySmall("No completed documents for current history filters.")}
      </div>
    </section>
  `;
}

function _renderInactiveOverduePanel(docs) {
  const overdue = docs
    .filter(doc => doc.state === "overdue" && !_isAcquisitionOnGoing(doc.projectStatus))
    .sort((a, b) => _parseAcquisitionDate(a.dueDate) - _parseAcquisitionDate(b.dueDate));

  return `
    <section class="acquisition-table-card acquisition-history-card">
      <div class="acquisition-history-heading">
        <h3>Inactive Overdue</h3>
        <span class="acquisition-count">${overdue.length} archived</span>
      </div>
      <div class="acquisition-history-list acquisition-inactive-overdue-list">
        ${overdue.length ? overdue.map(doc => `
          <div class="acquisition-history-item acquisition-inactive-overdue-item">
            <strong>${_escapeAcquisition(doc.project)}</strong>
            <span>${_escapeAcquisition(doc.name)} - ${_escapeAcquisition(doc.client)} - ${_escapeAcquisition(doc.de || "No DE")} - ${_escapeAcquisition(doc.projectStatus || "No status")} - ${_escapeAcquisition(_formatAcquisitionDate(doc.dueDate))}</span>
          </div>
        `).join("") : _renderAcquisitionEmptySmall("No inactive overdue documents for current filters.")}
      </div>
    </section>
  `;
}

function _renderCompletedHistory(docs) {
  const completed = docs
    .filter(doc => doc.state === "completed")
    .sort((a, b) => _parseAcquisitionDate(b.dueDate) - _parseAcquisitionDate(a.dueDate))
    .slice(0, 14);

  return `
    <section class="acquisition-table-card">
      <h3>Completed History</h3>
      <div class="acquisition-history-list">
        ${completed.length ? completed.map(doc => `
          <div class="acquisition-history-item">
            <strong>${_escapeAcquisition(doc.project)}</strong>
            <span>${_escapeAcquisition(doc.name)} · ${_escapeAcquisition(doc.client)} · ${_escapeAcquisition(_formatAcquisitionDate(doc.dueDate))}</span>
          </div>
        `).join("") : _renderAcquisitionEmptySmall("No completed documents for current filters.")}
      </div>
    </section>
  `;
}

function _renderAcquisitionEmptySmall(message, compact = false) {
  return `
    <div class="acquisition-empty ${compact ? "acquisition-empty-compact" : ""}">
      <i class="fa-regular fa-circle-check"></i>
      <span>${_escapeAcquisition(message)}</span>
    </div>
  `;
}

function _bindAcquisitionEvents() {
  _upgradeAcquisitionDocTiles();

  const refresh = document.getElementById("acquisitionRefreshBtn");
  if (refresh) refresh.addEventListener("click", () => carregarAcquisition(true));

  const search = document.getElementById("acquisitionSearch");
  if (search) search.addEventListener("input", event => {
    acquisitionState.filters.search = event.target.value;
    _renderAcquisitionFromTyping();
    const nextSearch = document.getElementById("acquisitionSearch");
    if (nextSearch) {
      nextSearch.focus();
      nextSearch.setSelectionRange(nextSearch.value.length, nextSearch.value.length);
    }
  });

  [
    ["acquisitionWeek", "week"],
    ["acquisitionDe", "de"],
    ["acquisitionClient", "client"]
  ].forEach(([id, key]) => {
    const select = document.getElementById(id);
    if (select) select.addEventListener("change", event => {
      acquisitionState.filters[key] = event.target.value;
      renderAcquisition();
    });
  });

  const historySearch = document.getElementById("acquisitionHistorySearch");
  if (historySearch) historySearch.addEventListener("input", event => {
    acquisitionState.historyFilters.search = event.target.value;
    _renderAcquisitionFromTyping();
    const nextSearch = document.getElementById("acquisitionHistorySearch");
    if (nextSearch) {
      nextSearch.focus();
      nextSearch.setSelectionRange(nextSearch.value.length, nextSearch.value.length);
    }
  });

  [
    ["acquisitionHistoryDocument", "document"],
    ["acquisitionHistoryMonth", "month"]
  ].forEach(([id, key]) => {
    const select = document.getElementById(id);
    if (select) select.addEventListener("change", event => {
      acquisitionState.historyFilters[key] = event.target.value;
      renderAcquisition();
    });
  });
}

function _renderAcquisitionFromTyping() {
  acquisitionState.quietRender = true;
  renderAcquisition();

  window.requestAnimationFrame(() => {
    acquisitionState.quietRender = false;
  });
}

function _upgradeAcquisitionDocTiles() {
  document.querySelectorAll(".acquisition-doc-chip").forEach(chip => {
    const text = chip.textContent || "";
    const parts = text.split(/\s+\u00C2?\u00B7\s+/);
    const name = parts[0] || text;
    const date = parts.slice(1).join(" - ");

    chip.classList.remove("acquisition-doc-chip");
    chip.classList.add("acquisition-doc-tile");
    chip.innerHTML = `
      <strong>${_escapeAcquisition(name)}</strong>
      <small>${_escapeAcquisition(date)}</small>
    `;
  });
}

function _groupDocsByProject(docs) {
  const map = new Map();
  docs.forEach(doc => {
    const key = doc.projectId || doc.project;
    if (!map.has(key)) {
      map.set(key, {
        project: doc.project,
        client: doc.client,
        de: doc.de,
        status: doc.projectStatus,
        docs: []
      });
    }
    map.get(key).docs.push(doc);
  });
  return [...map.values()];
}

function _groupAcquisitionDocs(docs, key) {
  const map = new Map();
  docs.forEach(doc => {
    const name = doc[key] || "Not defined";
    if (!map.has(name)) {
      map.set(name, { name, active: 0, overdue: 0 });
    }
    if (doc.state !== "completed") map.get(name).active += 1;
    if (doc.state === "overdue") map.get(name).overdue += 1;
  });
  return [...map.values()]
    .filter(row => row.active || row.overdue)
    .sort((a, b) => b.overdue - a.overdue || b.active - a.active || a.name.localeCompare(b.name));
}

function _countAcquisitionStates(docs) {
  return docs.reduce((acc, doc) => {
    const state = doc.state || "future";
    acc[state] = (acc[state] || 0) + 1;
    return acc;
  }, { completed: 0, overdue: 0, onTime: 0, future: 0 });
}

function _isAcquisitionOnGoing(status) {
  return _normalizeAcquisitionSearch(status).replace(/\s+/g, " ") === "on going";
}

function _formatAcquisitionDate(value) {
  const date = _parseAcquisitionDate(value);
  if (Number.isNaN(date.getTime())) return String(value || "No date");
  return date.toLocaleDateString("en-US", { month: "short", day: "2-digit" });
}

function _formatAcquisitionDateTime(value) {
  if (!value) return "Not loaded";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return String(value);
  return date.toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit"
  });
}

function _formatAcquisitionMonthKey(value) {
  const date = _parseAcquisitionDate(value);
  if (Number.isNaN(date.getTime())) return "";
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
}

function _formatAcquisitionMonthLabel(value) {
  const date = _parseAcquisitionDate(value);
  if (Number.isNaN(date.getTime())) return String(value || "No month");
  return date.toLocaleDateString("en-US", { month: "short", year: "numeric" });
}

function _daysFromToday(value) {
  const date = _parseAcquisitionDate(value);
  if (Number.isNaN(date.getTime())) return 0;
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  date.setHours(0, 0, 0, 0);
  return Math.round((date - today) / 86400000);
}

function _parseAcquisitionDate(value) {
  const text = String(value || "");
  const match = text.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (match) {
    return new Date(Number(match[1]), Number(match[2]) - 1, Number(match[3]));
  }
  return new Date(value);
}

function _escapeAcquisition(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function _normalizeAcquisitionSearch(value) {
  return String(value || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();
}

function _normalizeAcquisitionPerson(value) {
  const text = String(value || "").trim().replace(/\s+/g, " ");
  return _isValidAcquisitionPerson(text) ? text : "";
}

function _isValidAcquisitionPerson(value) {
  const text = String(value || "").trim();
  if (!text) return false;
  if (/^\d{1,2}[/-]\d{1,2}[/-]\d{2,4}$/.test(text)) return false;
  if (/^\d{4}-\d{2}-\d{2}$/.test(text)) return false;
  if (!/[A-Za-zÀ-ÿ]/.test(text)) return false;
  if (/[/:]/.test(text) && /\d/.test(text)) return false;
  return true;
}

function _normalizarAcquisitionId(value) {
  return _normalizeAcquisitionSearch(value)
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}
